# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
# Too many and Neo4j gets overwhelmed. 10 is the default concurrency Neo4j can handle.
:concurrency: 9
# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 30
:queues:
  - [critical, 3]
  - [default, 2]
  - [low, 1]
