source 'https://rubygems.org' do

  # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
  gem 'rails', '4.2.0'
  # Use SCSS for stylesheets
  gem 'sass-rails', '~> 5.0'
  # Use Uglifier as compressor for JavaScript assets
  gem 'uglifier', '>= 1.3.0'
  # Use CoffeeScript for .coffee assets and views
  gem 'coffee-rails', '~> 4.1.0'
  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', platforms: :ruby

  # Templating
  gem 'slim-rails'

  # Use jquery as the JavaScript library
  gem 'jquery-rails'
  # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
  gem 'jbuilder', '~> 2.0'
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', '~> 0.4.0', group: :doc

  # DB
  gem 'mongoid'
  gem 'neo4j'

  # Use ActiveModel has_secure_password
  # gem 'bcrypt', '~> 3.1.7'

  # Use Unicorn as the app server
  # gem 'unicorn'

  # Use Capistrano for deployment
  # gem 'capistrano-rails', group: :development

  group :development do
    gem 'guard-rspec', require: false
    gem 'zeus', require: false
  end

  group :development, :test do
    # Call 'byebug' anywhere in the code to stop execution and get a debugger console
    gem 'byebug'

    gem 'better_errors'
    gem 'binding_of_caller'

    gem 'rspec-rails'
    gem 'factory_girl_rails'
  end

  group :test do
    gem 'rspec-its'
    gem 'database_cleaner'
    gem 'capybara', require: ['capybara', 'capybara/dsl']
  end

  # API
  gem 'grape'

  # Organize business logic
  gem 'interactor'

  # Play nice with Grape's parameter validation
  gem 'hashie_rails'

  group :authorization do
    gem 'omniauth'
    gem 'omniauth-facebook'
    gem 'omniauth-google-oauth2'
  end
end